export const MINUTE_IN_SECONDS = 60;
export const HOUR_IN_SECONDS = 60 * MINUTE_IN_SECONDS;
export const DAY_IN_SECONDS = 24 * HOUR_IN_SECONDS;
export const WEEK_IN_SECONDS = 7 * DAY_IN_SECONDS;
export const MONTH_IN_SECONDS = 30 * DAY_IN_SECONDS;
export const YEAR_IN_SECONDS = 365 * DAY_IN_SECONDS;

export const NAV_ROUTES = [
  { name: "Projects", path: "/projects" },
  { name: "Gallery", path: "/gallery" },
  { name: "Services", path: "/services" },
  { name: "About", path: "/about" },
  // { name: "FAQ", path: "/faq" },
  { name: "Contact Us", path: "/contact" },
];

export const PROJECTS = [
  {
    id: "ab1bc2cc-078a-4bd4-887d-8c283c79dfb3",
    name: "Proposed Ariyo Catholic School (Learning Institute)",
    category: "Institutional",
    status: "Completed",
    client: "Ethiopia Catholic Church Society of Jesus",
    value: "28,476,075.52",
    location: "Bonga, Keffa",
    img: "/work1.jpg",
  },
  {
    id: "ab1bc2cc-078b-4bd4-887d-8c283c79dfb3",
    name: "Proposed Ariyo Residence (G+1)",
    category: "Institutional",
    status: "Completed",
    client: "Ethiopia Catholic Church Society of Jesus",
    value: "28,476,075.52",
    location: "Bonga, Keffa",
    img: "/pal39.jpg",
  },
  {
    id: "f0eed892-3e28-4f8e-bb3d-b1fae023358a",
    name: "Mixed-Use Building (B+G+6) Structural Work",
    category: "Commercial",
    status: "Completed",
    client: "Ene W/ro Belay Tesfaye",
    value: "19,580,858.65",
    location: "Addis Ababa",
    img: "/work4.png",
  },
  {
    id: "591938dc-354a-4276-beba-ccd4ea42a4ae",
    name: "Mixed-Use Building (B+G+5)",
    category: "Commercial",
    status: "Completed",
    client: "W/ro Etenesh Haile",
    value: "9,789,682.22",
    location: "Addis Ababa",
    img: "/work6.png",
  },
  {
    id: "ee6fe3d4-4e23-485d-b7b7-d4c87c00591c",
    name: "New Project",
    category: "Commercial",
    status: "Completed",
    client: "Unknown",
    value: "1,181,868.92",
    location: "Addis Ababa",
    img: "/work14.jpg",
  },
  {
    id: "08479ce4-c33f-4458-a9c5-ded50e129c7c",
    name: "Mixed-Use Building (B+G+6) Finishing Work",
    category: "Commercial",
    status: "Completed",
    client: "Ene Belay Tesfaye",
    value: "4,235,042.90",
    location: "Addis Ababa",
    img: "/work8.png",
  },
  {
    id: "dbadcbc7-da1c-4905-8d3c-7fa24779d937",
    name: "Residence Building (2+B+G+3)",
    category: "Residential",
    status: "Completed",
    client: "W/ro Senait G/Gziabher",
    value: "6,464,859.31",
    location: "Addis Ababa",
    img: "/work3.png",
  },
  {
    id: "fb1d7c81-0601-4070-9b3c-0806ac4109ad",
    name: "Residence Building (2+B+G+3)",
    category: "Residential",
    status: "Completed",
    client: "Art. Ephrem Tamiru",
    value: "10,776,989.85",
    location: "Addis Ababa",
    img: "/work5.png",
  },
  {
    id: "3fcd4652-3653-46a3-b772-68016abf256a",
    name: "Mixed-Use Building (B+G+6) Structural Work",
    category: "Commercial",
    status: "Completed",
    client: "Ato Girma Amare & W/ro Martha Negash",
    value: "8,008,878.53",
    location: "Addis Ababa",
    img: "/work7.png",
  },
  {
    id: "48f6d1a1-6eb5-455e-8daa-9c57d3f4e060",
    name: "Residence Building (B+G+2)",
    category: "Residential",
    status: "Completed",
    client: "Dr. Atnafu Tola",
    value: "3,551,588.89",
    location: "Addis Ababa",
    img: "/work9.png",
  },
  {
    id: "e3cc4faf-ff69-408a-a91e-9303a52d15b8",
    name: "Mixed-Use Building (B+G+5)",
    category: "Commercial",
    status: "Completed",
    client: "W/ro Misrak Elias",
    value: "2,180,277.90",
    location: "Addis Ababa",
    img: "/work10.png",
  },
  {
    id: "7c99a343-33ad-4e1d-b0ea-61899b75c0b8",
    name: "Mixed Use Building (B+G+6) Finishing Work",
    category: "Commercial",
    status: "Under Construction",
    client: "Ato Girma Amare & W/ro Martha Negash",
    value: "4,870,151.85",
    location: "Addis Ababa",
    img: "/work2.png",
  },
  {
    id: "aa121116-aafe-4a23-8351-207e7d72ca83",
    name: "Apartment Building Construction (G+5)",
    category: "Residential",
    status: "Completed",
    client: "Tigist Asefa",
    value: "2,165,583.40",
    location: "Addis Ababa",
    img: "/work11.png",
  },
  {
    id: "ee6fe3d4-4e76-485d-b7b7-d4c87c00591c",
    name: "Kera Store Maintenance Work",
    category: "Commercial",
    status: "Completed",
    client: "BGI Ethiopia PLC",
    value: "1,181,868.92",
    location: "Addis Ababa",
    img: "/work12.png",
  },
];
