export const MINUTE_IN_SECONDS = 60;
export const HOUR_IN_SECONDS = 60 * MINUTE_IN_SECONDS;
export const DAY_IN_SECONDS = 24 * HOUR_IN_SECONDS;
export const WEEK_IN_SECONDS = 7 * DAY_IN_SECONDS;
export const MONTH_IN_SECONDS = 30 * DAY_IN_SECONDS;
export const YEAR_IN_SECONDS = 365 * DAY_IN_SECONDS;

export const NAV_ROUTES = [
  { name: "Services", path: "/services" },
  { name: "Work", path: "/work" },
  { name: "Gallery", path: "/gallery" },
  { name: "About", path: "/about" },
  { name: "FAQ", path: "/faq" },
  { name: "Contact Us", path: "/contact" },
];

export const PROJECTS = [
  {
    id: "mixed-use-bg6-finishing-1",
    name: "Mixed-Use Building (B+G+6) Finishing Work",
    category: "Commercial",
    status: "Under Construction",
    client: "Ato Girma Amare & W/ro Martha Negash",
    value: "4,870,151.85",
    location: "Addis Ababa",
    img: "/work2.png",
  },
  {
    id: "residence-2bg3-senait",
    name: "Residence Building (2+B+G+3)",
    category: "Residential",
    status: "Completed",
    client: "W/ro Senait G/Gziabher",
    value: "6,464,859.31",
    location: "Addis Ababa",
    img: "/work3.png",
  },
  {
    id: "mixed-use-bg6-structural-1",
    name: "Mixed-Use Building (B+G+6) Structural Work",
    category: "Commercial",
    status: "Completed",
    client: "Ene W/ro Belay Tesfaye",
    value: "19,580,858.65",
    location: "Addis Ababa",
    img: "/work4.png",
  },
  {
    id: "residence-2bg3-ephrem",
    name: "Residence Building (2+B+G+3)",
    category: "Residential",
    status: "Completed",
    client: "Art. Ephrem Tamiru",
    value: "10,776,989.85",
    location: "Addis Ababa",
    img: "/work5.png",
  },
  {
    id: "mixed-use-bg5-etenesh",
    name: "Mixed-Use Building (B+G+5)",
    category: "Commercial",
    status: "Completed",
    client: "W/ro Etenesh Haile",
    value: "9,789,682.22",
    location: "Addis Ababa",
    img: "/work6.png",
  },
  {
    id: "mixed-use-bg6-structural-2",
    name: "Mixed-Use Building (B+G+6) Structural Work",
    category: "Commercial",
    status: "Completed",
    client: "Ato Girma Amare & W/ro Martha Negash",
    value: "8,008,878.53",
    location: "Addis Ababa",
    img: "/work7.png",
  },
  {
    id: "mixed-use-bg6-finishing-2",
    name: "Mixed-Use Building (B+G+6) Finishing Work",
    category: "Commercial",
    status: "Completed",
    client: "Ene Belay Tesfaye",
    value: "4,235,042.90",
    location: "Addis Ababa",
    img: "/work8.png",
  },
  {
    id: "residence-bg2-atnafu",
    name: "Residence Building (B+G+2)",
    category: "Residential",
    status: "Completed",
    client: "Dr. Atnafu Tola",
    value: "3,551,588.89",
    location: "Addis Ababa",
    img: "/work9.png",
  },
  {
    id: "mixed-use-bg5-misrak",
    name: "Mixed-Use Building (B+G+5)",
    category: "Commercial",
    status: "Completed",
    client: "W/ro Misrak Elias",
    value: "2,180,277.90",
    location: "Addis Ababa",
    img: "/work10.png",
  },
  {
    id: "apartment-g5-tigist",
    name: "Apartment Building Construction (G+5)",
    category: "Residential",
    status: "Completed",
    client: "Tigist Asefa",
    value: "2,165,583.40",
    location: "Addis Ababa",
    img: "/work11.png",
  },
  {
    id: "kera-store-maintenance",
    name: "Kera Store Maintenance Work",
    category: "Commercial",
    status: "Completed",
    client: "BGI Ethiopia PLC",
    value: "1,181,868.92",
    location: "Addis Ababa",
    img: "/work12.png",
  },
  {
    id: "ariyo-catholic-g1-residence",
    name: "Ariyo Catholic Learning Institute (G+1 Residence)",
    category: "Institutional",
    status: "Completed",
    client: "Ethiopia Catholic Church Society of Jesus",
    value: "28,476,075.52",
    location: "Bonga, Keffa",
    img: "/work1.png",
  },
];
